# Generated by Django 4.0.3 on 2022-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('political_party', models.CharField(max_length=20)),
            ],
        ),
    ]
