# Generated by Django 4.1.4 on 2023-01-05 18:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_personaldatamodel_emaillistconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
